allowBuilds:
  esbuild: true
blockExoticSubdeps: true
trustPolicy: no-downgrade
trustPolicyExclude:
  - semver@6.3.1
minimumReleaseAge: 4320
minimumReleaseAgeExclude:
  - eslint@10.8.0
  - "@typescript-eslint/types@8.66.0"

packages:
  - "."
