name: Frontend-Photobogota

"on":
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch: #Para poder correr el workflow manualmente

# Permisos necesarios para que el Action pueda escribir en la rama gh-pages
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout del código
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Instalar pnpm
        uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v4.4.0
        with:
          version: 9 # la versión que estemos usando

      - name: Configurar Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"

      - name: Instalar dependencias
        run: pnpm install --frozen-lockfile --ignore-scripts

      - name: Construir proyecto (Vite)
        run: pnpm run build
        env:
          VITE_BASE_PATH: /Frontend-Photobogota/

      - name: Deploy
        if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
        uses: JamesIves/github-pages-deploy-action@fa24774553152dd7873cd16ebd8d959b010c5445 # v4.9.0
        with:
          folder: dist
          branch: gh-pages
